name: Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version (ex: 1.0.0)'
        required: true
      nextSnapshotVersion:
        description: 'Next SNAPSHOT version (ex: 1.0.1-SNAPSHOT)'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    environment: prod
    env:
      DOCKER_IMAGE: web-semantic-pfm:${{ github.event.inputs.releaseVersion }}
      DOCKER_IMAGE_TAG: zarayach/web-semantic-pfm:${{ github.event.inputs.releaseVersion }}
    steps:
      - name: Print entered versions
        run: |
          echo "Release version: ${{ github.event.inputs.releaseVersion }}"
          echo "Next SNAPSHOT version: ${{ github.event.inputs.nextSnapshotVersion }}"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to the Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: Creating release branch and publishing version to registry
        env:
          BUILD_ENV: 'github-actions'
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git checkout -b release/v${{ github.event.inputs.releaseVersion }}
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }} -DgenerateBackupPoms=false
          mvn -B package
          docker build -t $DOCKER_IMAGE .
          docker tag $DOCKER_IMAGE $DOCKER_IMAGE_TAG
          docker push $DOCKER_IMAGE_TAG
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git commit -am 'Creating release version ${{ github.event.inputs.releaseVersion }}'
          git push origin release/v${{ github.event.inputs.releaseVersion }} --force
      - name: Publishing release and tags in github
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.event.inputs.releaseVersion }}
          release_name: Release ${{ github.event.inputs.releaseVersion }}
          draft: false
          prerelease: false
      - name: Preparing next SNAPSHOT version for development
        env:
          BUILD_ENV: 'github-actions'
        run: |
          git checkout -b v${{ github.event.inputs.nextSnapshotVersion }}
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.nextSnapshotVersion }} -DgenerateBackupPoms=false
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git commit -am 'Updating version to ${{ github.event.inputs.nextSnapshotVersion }}'
          git push origin v${{ github.event.inputs.nextSnapshotVersion }} --force
      - name: Creating pull request to merge to master
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ github.token }}
          source_branch: v${{ github.event.inputs.nextSnapshotVersion }}
          pr_title: "Merge v${{ github.event.inputs.nextSnapshotVersion }} into master"
          pr_body: |
            Hi!
            This PR was created in response release workflow running. 
            I've created release ${{ github.event.inputs.releaseVersion }}. 
            Updating master for next iteration version ${{ github.event.inputs.nextSnapshotVersion }}.
          pr_allow_empty: true
          pr_reviewer: ${{ github.actor }}
          pr_assignee: ${{ github.actor }}
          pr_label: "version update 🚀"
      - name: Clean up Docker images and containers
        run: |
          docker rmi -f $DOCKER_IMAGE_TAG $DOCKER_IMAGE
          docker system prune --force
